services:
  mysqldb:
    image: mysql:8.0
    container_name: SAproject
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ../database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: maindb 
      MYSQL_USER: admin
      MYSQL_PASSWORD: 2023sap
      MYSQL_ROOT_PASSWORD: 2023sap
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
